{
  "openapi":"3.0.2",
  "info": {
    "title":"TodoList RESTful API",
    "version":"1.0",
    "description": "Dokumentasi OpenAPI for TodoList RESTful API",
    "termsOfService": "https://www.bayubagusbagaswara",
    "contact": {
        "name": "Bayu Bagus Bagaswara",
        "email": "bayubagusbagaswara@gmail.com",
        "url": "https://www.bayubagusbagaswara.com"
    },
    "license": {
        "name": "APACHE 2.0",
        "url": "http://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "TodoList RESTful API Server",  
      "url":"https://{environment}.bayubagusbagaswara.com/api/v1",
      "variables": {
        "environment" : {
          "description": "Server Environment",
          "default": "dev",
          "enum": [
            "dev",
            "qa",
            "prod"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Youtube Programmer Zaman Now",
    "url": "https://www.youtube.com/c/ProgrammerZamanNow"
  },
  "paths": {
    "/todolist" : {
      "get" : {
        "tags": ["Todolist"],
        "summary": "Get All Todolist",
        "description": "Get all active todolist by default",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "Is include done todolist",
            "schema" : {
              "type": "boolean"
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema" : {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            },
            "examples" : {
              "java" : {
                "value" : "Java",
                "description": "Example name Java"
              },
              "php" : {
                "value" : "PHP",
                "description": "Example name PHP"
              }
            }
          }
        ],
        "responses": {
          "200" : {
            "description": "Success get all todolist",
            "content": {
              "application/json" : {
                "schema" : {
                  "type": "array",
                  "items" : {
                    "type": "object",
                    "properties": {
                      "id" : {
                        "type": "string"
                      },
                      "name" : {
                        "type": "string"
                      }, 
                      "priority" : {
                        "type": "number",
                        "format": "int32"
                      },
                      "tags" : {
                        "type": "array",
                        "items" : {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success" : {
                    "description": "Example success get all todolist",
                    "value" : [
                      {
                        "id" : "1",
                        "name" : "Java",
                        "priority" : 3,
                        "tags" : [
                          "Java", "Programming"
                        ]
                      },
                      {
                        "id" : "2",
                        "name" : "PHP",
                        "priority" : 5,
                        "tags" : [
                          "PHP", "Programming"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags": ["Todolist"],
        "summary": "Create New Todolist",
        "description": "Create new todolist to database",
        "requestBody" : {
          "required": true,
          "content": {
            "application/json" : {
              "schema" : {
                "type": "object",
                "properties": {
                  "name" : {
                    "type": "string",
                    "minLength": 1,
                    "required":true
                  },
                  "priority" : {
                    "type": "integer",
                    "format": "int32",
                    "default": 1,
                    "required": true
                  },
                  "tags" : {
                    "type": "array",
                    "required": false,
                    "minItems": 1,
                    "items" : {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "java" : {
                  "description": "Example create todolist Java",
                  "value": {
                    "name" : "Java",
                    "priority" : 3,
                    "tags" : [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php" : {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name" : "PHP",
                    "priority" : 5,
                    "tags" : [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200" : {
            "description": "Success create todolist",
            "content": {
              "application/json" : {
                "schema" : {
                  "type": "object",
                  "properties": {
                    "id" : {
                    "type": "string"
                    },
                    "name" : {
                    "type": "string"
                    }, 
                    "priority" : {
                    "type": "number",
                    "format": "int32"
                    },
                    "tags" : {
                      "type": "array",
                      "items" : {
                      "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "java" : {
                    "description": "Success create java todolist",
                    "value" : {
                      "id" : "1",
                      "name" : "Java",
                      "priority" : 3,
                      "tags" : [
                        "Java",
                        "Programming"
                      ]
                    }
                  },
                  "php" : {
                    "description": "Success create PHP todolist",
                    "value" : {
                      "id" : "2",
                      "name" : "PHP",
                      "priority" : 5,
                      "tags" : [
                        "PHP",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todolistId}" : {
      "put" : {
        "tags": ["Todolist"],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "Todolist id for updated",
            "schema" : {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java" : {
                "description": "Sample todolist id for Java",
                "value": "1"
              },
              "php" : {
                "description": "Sample todolist id for PHP",
                "value": "2"
              }
            }
          }
        ],
        "requestBody" : {
          "required": true,
          "content": {
            "application/json" : {
              "schema" : {
                "type": "object",
                "properties": {
                  "name" : {
                    "type": "string",
                    "minLength": 1,
                    "required": true
                  },
                  "priority" : {
                    "type": "integer",
                    "format": "int32",
                    "default": 1,
                    "required": true
                  },
                  "tags" : {
                    "type": "array",
                    "required": false,
                    "minItems": 1,
                    "items" : {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "java" : {
                  "description": "Example create todolist Java",
                  "value": {
                    "name" : "Java",
                    "priority" : 3,
                    "tags" : [
                      "Java",
                      "Programming"
                    ]
                  }
                },
                "php" : {
                  "description": "Example create todolist PHP",
                  "value": {
                    "name" : "PHP",
                    "priority" : 5,
                    "tags" : [
                      "PHP",
                      "Programming"
                    ]
                  }
                }
              }
              
            }
          }
        },
        "responses": {
          "200" : {
            "description": "Success update todolist",
            "content": {
              "application/json" : {
                "schema" : {
                  "type": "object",
                  "properties": {
                    "id" : {
                    "type": "string"
                    },
                    "name" : {
                    "type": "string"
                    }, 
                    "priority" : {
                    "type": "number",
                    "format": "int32"
                    },
                    "tags" : {
                      "type": "array",
                      "items" : {
                      "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "java" : {
                    "description": "Success create java todolist",
                    "value" : {
                      "id" : "1",
                      "name" : "Java",
                      "priority" : 3,
                      "tags" : [
                        "Java",
                        "Programming"
                      ]
                    }
                  },
                  "php" : {
                    "description": "Success create PHP todolist",
                    "value" : {
                      "id" : "2",
                      "name" : "PHP",
                      "priority" : 5,
                      "tags" : [
                        "PHP",
                        "Programming"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete" : {
        "tags": ["Todolist"],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "name": "todolistId",
            "in": "path",
            "required": true,
            "description": "Todolist id for deleted",
            "schema" : {
              "type": "string",
              "minLength": 1,
              "maxLength": 100
            }
          }
        ],
        "responses": {
          "200" : {
            "description": "Success delete todolist",
            "content": {
              "application/json": {
                "schema" : {
                  "type": "object",
                  "properties": {
                    "success" : {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success" : {
                    "description": "Success delete todolist",
                    "value" : {
                      "success" : true
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Failed delete not found todolist",
            "content": {
              "application/json": {
                "schema" : {
                  "type": "object",
                  "properties": {
                    "success" : {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed" : {
                    "description": "Failed delete todolist",
                    "value" : {
                      "success" : false
                    }
                  }
                }
              }
            }

          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "TodolistId" : {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "Todolist id for updated",
        "schema" : {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "java" : {
            "description": "Sample todolist id for Java",
            "value": "1"
          },
          "php" : {
            "description": "Sample todolist id for PHP",
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "Todolist" : {
        "type": "object",
        "properties": {
          "id" : {
            "type": "string"
          },
          "name" : {
            "type": "string"
          }, 
          "priority" : {
            "type": "number",
            "format": "int32"
          },
          "tags" : {
            "type": "array",
            "items" : {
              "type": "string"
            }
          }
        }
      },
      "CreateOrUpdateTodolist" : {
        "type": "object",
        "properties": {
          "name" : {
            "type": "string"
          }, 
          "priority" : {
            "type": "number",
            "format": "int32"
          },
          "tags" : {
            "type": "array",
            "items" : {
              "type": "string"
            }
          }
        }
      },
      "ArrayTodolist" : {
        "type": "array",
        "items" : {
          "type": "object",
          "properties": {
            "id" : {
              "type": "string"
            },
            "name" : {
              "type": "string"
            }, 
            "priority" : {
              "type": "number",
              "format": "int32"
            },
            "tags" : {
              "type": "array",
              "items" : {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}